repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black backend/src
        language: system
        types: [ python ]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.12.0
    hooks:
      - id: black
        language_version: python3.12
