repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ['src']

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black backend/src
        language: system
        types: [ python ]
