repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black backend/src
        language: system
        types: [ python ]

      - id: isort
        name: isort
        entry: isort src
        language: system
        types: [ python ]
