# Generated by Django 4.2.8 on 2024-02-22 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MotorcycleBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("country_of_origin", models.CharField(max_length=256, null=True)),
                (
                    "year_established",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Motorcycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("displacement", models.PositiveIntegerField()),
                (
                    "drive_type",
                    models.CharField(
                        choices=[
                            ("Belt", "Belt"),
                            ("Chain", "Chain"),
                            ("Shaft", "Shaft"),
                        ],
                        max_length=256,
                    ),
                ),
                ("model", models.CharField(max_length=256)),
                (
                    "short_description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Adventure", "Adventure"),
                            ("Cruiser", "Cruiser"),
                            ("Dual Sport", "Dual Sport"),
                            ("Electric", "Electric"),
                            ("Naked", "Naked"),
                            ("Off-Road", "Off-Road"),
                            ("Other", "Other"),
                            ("Scooter", "Scooter"),
                            ("Scrambler", "Scrambler"),
                            ("Sport", "Sport"),
                            ("Standard", "Standard"),
                            ("Touring", "Touring"),
                        ],
                        max_length=256,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="motorcycle.motorcyclebrand",
                    ),
                ),
            ],
        ),
    ]
